#!/bin/sh

extension_files="manifest.json background.js blocked_domains.js icon*png ignore.jpg warning.*"

old_pwd=`pwd`
cd `dirname $0`

cp -f ../common/* .

rm -rf dancewithme && \
	mkdir dancewithme && \
	cp $extension_files dancewithme && \
	zip -r dancewithme.zip dancewithme/ && \
	rm -rf dancewithme

cd "$old_pwd"
